# Generated by Django 3.2.5 on 2021-07-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210725_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PRFCity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_City', to='accounts.city', verbose_name='City'),
        ),
    ]
