# Generated by Django 3.2.5 on 2021-07-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210724_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='JOBJobtype',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='', max_length=15, verbose_name='Job Type'),
            preserve_default=False,
        ),
    ]
