# Generated by Django 3.2.5 on 2021-07-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_jobdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='JOBCreated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='JOBExperience',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='JOBSalary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='JOBVacancy',
            field=models.IntegerField(default=1),
        ),
    ]
