# Generated by Django 3.2.5 on 2021-07-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20210724_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATName', models.CharField(max_length=50, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='JOBCreated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='job',
            name='JOBExperience',
            field=models.IntegerField(default=1, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='job',
            name='JOBSalary',
            field=models.IntegerField(default=0, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='job',
            name='JOBVacancy',
            field=models.IntegerField(default=1, verbose_name='Vacancy'),
        ),
    ]
