# Generated by Django 3.2.5 on 2021-07-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20210724_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='JOBCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.category', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
