# Generated by Django 3.2.5 on 2021-07-24 21:44

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_job_jobimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='JOBSlug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='job',
            name='JOBImage',
            field=models.ImageField(blank=True, null=True, upload_to=job.models.image_upload, verbose_name='Image'),
        ),
    ]
