# Generated by Django 3.2.5 on 2021-07-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20210724_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicatiion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APPName', models.CharField(max_length=50, verbose_name='Name')),
                ('APPEmail', models.EmailField(max_length=50, verbose_name='Email')),
                ('APPurl', models.URLField(verbose_name='URL')),
                ('APPCV', models.FileField(upload_to='apply/', verbose_name='CV')),
                ('APPCOver_letter', models.TextField(max_length=1000, verbose_name='Cover Letter')),
            ],
            options={
                'verbose_name': 'Applicatiion',
                'verbose_name_plural': 'Applicatiions',
            },
        ),
    ]
