# Generated by Django 3.2.5 on 2021-07-24 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_applicatiion'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicatiion',
            name='APPJob',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Job_application', to='job.job', verbose_name='Job ID'),
            preserve_default=False,
        ),
    ]
