# Generated by Django 3.2.5 on 2021-07-24 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_applicatiion_appjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicatiion',
            name='APPCreated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='applicatiion',
            name='APPJob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_application', to='job.job', verbose_name='Job'),
        ),
    ]
