# Generated by Django 3.2.5 on 2021-07-25 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0012_auto_20210725_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='JOBowner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_wner', to='auth.user', verbose_name='Job Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='PRFCountry',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
    ]
