# Generated by Django 3.2.5 on 2021-07-25 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0013_auto_20210725_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='JOBowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_owner', to=settings.AUTH_USER_MODEL, verbose_name='Job Owner'),
        ),
    ]
